# Kickstarter Projects
use the data from [this](https://www.kaggle.com/kemical/kickstarter-projects) source to predict if a project will sucess or not ? :

![card](kickstarter.jpg)

In [1]:
import pandas as pd
dataset = pd.read_csv('ks-projects-201801.csv')
dataset.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

In [2]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 15 columns):
ID                  378661 non-null int64
name                378657 non-null object
category            378661 non-null object
main_category       378661 non-null object
currency            378661 non-null object
deadline            378661 non-null object
goal                378661 non-null float64
launched            378661 non-null object
pledged             378661 non-null float64
state               378661 non-null object
backers             378661 non-null int64
country             378661 non-null object
usd pledged         374864 non-null float64
usd_pledged_real    378661 non-null float64
usd_goal_real       378661 non-null float64
dtypes: float64(5), int64(2), object(8)
memory usage: 31.8+ MB

In [3]:
dataset.launched = pd.to_datetime(dataset.launched)
dataset.deadline = pd.to_datetime(dataset.deadline)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 15 columns):
ID                  378661 non-null int64
name                378657 non-null object
category            378661 non-null object
main_category       378661 non-null object
currency            378661 non-null object
deadline            378661 non-null datetime64[ns]
goal                378661 non-null float64
launched            378661 non-null datetime64[ns]
pledged             378661 non-null float64
state               378661 non-null object
backers             378661 non-null int64
country             378661 non-null object
usd pledged         374864 non-null float64
usd_pledged_real    378661 non-null float64
usd_goal_real       378661 non-null float64
dtypes: datetime64[ns](2), float64(5), int64(2), object(6)
memory usage: 34.7+ MB

In [4]:
dataset['duration'] = dataset.deadline - dataset.launched

In [5]:
dataset['duration'] = dataset['duration'].apply(lambda x: x.days)

In [6]:
dataset.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,duration
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,58
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,59
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,44
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,29
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,55

In [7]:
dataset.isnull().sum()

ID                     0
name                   4
category               0
main_category          0
currency               0
deadline               0
goal                   0
launched               0
pledged                0
state                  0
backers                0
country                0
usd pledged         3797
usd_pledged_real       0
usd_goal_real          0
duration               0
dtype: int64

In [8]:
dataset.shape

(378661, 16)

In [6]:
def success (x) :
    if  x >= 1 :
        return 0
    else :
        return 1

In [44]:
# if dataset.loc[dataset['goal'] < dataset['pledged']]:
#     dataset['success'] = 1
# else :
#     dataset['success'] = 0

In [7]:
dataset['success'] = dataset.goal - dataset.pledged

In [8]:
dataset.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,duration,success
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,58,1000.0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,59,27579.0
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,44,44780.0
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,29,4999.0
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,55,18217.0

In [10]:
dataset['success'] = dataset['success'].apply(success)
dataset.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,duration,success
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,58,1
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,59,1
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,44,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,29,1
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,55,1

In [11]:
dataset['success'].value_counts()

1    241610
0    137051
Name: success, dtype: int64

In [12]:
for col in dataset.columns :
    print (col , len(dataset[col].unique()))

ID 378661
name 375765
category 159
main_category 15
currency 14
deadline 3164
goal 8353
launched 378089
pledged 62130
state 6
backers 3963
country 23
usd pledged 95456
usd_pledged_real 106065
usd_goal_real 50339
duration 99
success 2

In [13]:
dataset.isna().sum()

ID                     0
name                   4
category               0
main_category          0
currency               0
deadline               0
goal                   0
launched               0
pledged                0
state                  0
backers                0
country                0
usd pledged         3797
usd_pledged_real       0
usd_goal_real          0
duration               0
success                0
dtype: int64

In [16]:
dataset = dataset.drop(columns=['ID','name','currency','deadline','launched','goal','pledged','state','country','usd pledged','usd_pledged_real','usd_goal_real'])
dataset

KeyError: "['ID' 'name' 'currency' 'deadline' 'launched' 'goal' 'pledged' 'state'\n 'country' 'usd pledged' 'usd_pledged_real' 'usd_goal_real'] not found in axis"

In [56]:
dataset.isna().sum()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 5 columns):
category         378661 non-null object
main_category    378661 non-null object
backers          378661 non-null int64
duration         378661 non-null int64
success          378661 non-null int64
dtypes: int64(3), object(2)
memory usage: 11.6+ MB

In [17]:
x = dataset.iloc[:,:-1]
x

               category main_category  backers  duration
0                Poetry    Publishing        0        58
1        Narrative Film  Film & Video       15        59
2        Narrative Film  Film & Video        3        44
3                 Music         Music        1        29
4          Film & Video  Film & Video       14        55
...                 ...           ...      ...       ...
378656      Documentary  Film & Video        1        29
378657   Narrative Film  Film & Video        5        26
378658   Narrative Film  Film & Video        1        45
378659       Technology    Technology        6        30
378660  Performance Art           Art       17        27

[378661 rows x 4 columns]

In [18]:
x= pd.get_dummies(x)
x

,backers,duration,category_3D Printing,category_Academic,category_Accessories,category_Action,category_Animals,category_Animation,category_Anthologies,category_Apparel,...,main_category_Fashion,main_category_Film & Video,main_category_Food,main_category_Games,main_category_Journalism,main_category_Music,main_category_Photography,main_category_Publishing,main_category_Technology,main_category_Theater
0,0,58,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,15,59,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,3,44,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,29,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,14,55,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,1,29,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
378657,5,26,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
378658,1,45,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
378659,6,30,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
378660,17,27,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
y = dataset.iloc[:,-1]
y

0         1
1         1
2         1
3         1
4         1
         ..
378656    1
378657    1
378658    1
378659    1
378660    1
Name: success, Length: 378661, dtype: int64

In [61]:
# # standrize the values
# from sklearn.preprocessing import StandardScaler , MinMaxScaler
# scaler = MinMaxScaler()
# x = scaler.fit_transform(x)

In [20]:
from sklearn.model_selection import train_test_split ,GridSearchCV
x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 ,random_state=0)

In [65]:
# from sklearn.neighbors import KNeighborsClassifier 
# cl = KNeighborsClassifier(n_neighbors = 22)
# cl.fit(x_train,y_train)
# from sklearn.linear_model import LogisticRegression
# cl = LogisticRegression(random_state = 0)
# cl.fit(x_train,y_train)

MemoryError:

In [28]:
from sklearn.tree import DecisionTreeClassifier , plot_tree
dtclf = DecisionTreeClassifier(max_depth = 8, min_samples_leaf = 7)
dtclf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=8,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=7, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [23]:
parameters = [{'min_samples_leaf':[2,5,7],'max_depth':[5,7,8]}]
grid_search = GridSearchCV(estimator = dtclf , param_grid = parameters , cv=10 , n_jobs = -1)
grid_search = grid_search.fit(x_train, y_train)
print("best accuracy is :" , grid_search.best_score_)
grid_search.best_params_

best accuracy is : 0.8622114825965246

{'max_depth': 8, 'min_samples_leaf': 7}

In [30]:
y_pred = dtclf.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix ,f1_score , precision_score ,recall_score ,classification_report
cm = confusion_matrix(y_test, y_pred)
print (pd.DataFrame(cm))
print(classification_report(y_test, y_pred))

       0      1
0  22252   5138
1   5468  42875
              precision    recall  f1-score   support

           0       0.80      0.81      0.81     27390
           1       0.89      0.89      0.89     48343

    accuracy                           0.86     75733
   macro avg       0.85      0.85      0.85     75733
weighted avg       0.86      0.86      0.86     75733

In [34]:
from sklearn.ensemble import RandomForestClassifier , AdaBoostClassifier , VotingClassifier ,StackingClassifier ,GradientBoostingClassifier
forest = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=1)
forest.fit(x_train,y_train)
y_pred = dtclf.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print (pd.DataFrame(cm))
print(classification_report(y_test, y_pred))

MemoryError: could not allocate 6291456 bytes

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(random_state=1)
clf2 = LinearSVC(random_state=1)
clf3 = GaussianNB()
lr = LogisticRegression()
vclf = VotingClassifier(estimators=[('lr', clf1), ('svc', clf2), ('gnb', clf3)], voting='hard')
vclf.fit(x_train,y_train)
vclf.score(x_test,y_test)

In [ ]:
adaclf = AdaBoostClassifier(n_estimators=100)

In [ ]:
gbclf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)

In [ ]:
sclf = StackingClassifier(classifiers=[clf1, clf2, clf3], meta_classifier=lr)